### ISSUE TITLE
[Help] All available commands 

### ISSUE THREAD

**Issue by AzadKshitij** [Civitasv/nvimrc#1]
Can you share all available commands so the new comer can understand how to use it.

**Comment by Civitasv** [comment]
hi, do you mean key maps? Cause there're plenty commands that I don't know in neovim and plugins.

**Comment by AzadKshitij** [comment]
Yes, I mean the same 
Some commands for getting started with tree view and command line would be helpful.

**Comment by Civitasv** [comment]
I just add docs for keymaps. See https://github.com/Civitasv/runvim/blob/master/keymaps.md.
Hope this will help you.

**Comment by AzadKshitij** [comment]
Thanks this is very useful.
