### ISSUE TITLE
nvim/lua/user/colorscheme.lua:12: module 'catppucc not found

### ISSUE THREAD

**Issue by CnsMaple** [Civitasv/nvimrc#4]
When I installed in Windows, I encountered this problem. What should I do?

I only installed neovim, not packer.nvim. Should I go to Ubuntu to install it? Does Ubuntu installation have this problem?
![image](https://user-images.githubusercontent.com/92523839/212405588-ce9d7ece-bc65-4eea-a975-9a3ce0645e35.png)
After this problem occurred, I tried to install packer.nvim. But this error still occurs.
My neovim version is 0.8.2 (stable)
My Windows version is 11

**Comment by Civitasv** [comment]
Navigate to lua/user/plugins.lua, and then save it, it will automatically install all the required plugins.

**Comment by CnsMaple** [comment]
Not only this plug-in, but after I added this plug-in, other plug-ins also reported errors, which is a bit troublesome. Is there a method that can be used directly after clone?

**Comment by Civitasv** [comment]
Sorry about that, currently not.
