### ISSUE TITLE
Cmake module missing

### ISSUE THREAD

**Issue by cainydev** [Civitasv/nvimrc#5]
I just cloned the repo into the .config/nvim directory. On startup it installed a whole lot of stuff with lazy but on the next start I got this error:

```
Failed to run `config` for lualine.nvim
/home/john/.config/nvim/lua/plugins/lualine.lua:6: module 'cmake-tools' not found:
^Ino field package.preload['cmake-tools']
lazy_loader: module cmake-tools not found
lazy_loader_lib: module cmake-tools not found
^Ino file './cmake-tools.lua'
^Ino file '/usr/share/luajit-2.1.0-beta3/cmake-tools.lua'
^Ino file '/usr/local/share/lua/5.1/cmake-tools.lua'
^Ino file '/usr/local/share/lua/5.1/cmake-tools/init.lua'
^Ino file '/usr/share/lua/5.1/cmake-tools.lua'
^Ino file '/usr/share/lua/5.1/cmake-tools/init.lua'
^Ino file './cmake-tools.so'
^Ino file '/usr/local/lib/lua/5.1/cmake-tools.so'
^Ino file '/usr/lib/lua/5.1/cmake-tools.so'
^Ino file '/usr/local/lib/lua/5.1/loadall.so'
# stacktrace:
  - .config/nvim/lua/plugins/lualine.lua:6 _in_ **config**
  - .config/nvim/init.lua:1
```

and this warning:
```
view.mappings.list has been deprecated in favour of on_attach. Please run :NvimTreeGenerat
eOnAttach and visit https://github.com/nvim-tree/nvim-tree.lua/wiki/Migrating-To-on_attach
```

and this error:
```
Failed to run `config` for cmake-tools.nvim
/home/john/.config/nvim/lua/plugins/cmake.lua:4: module 'cmake-tools' not found:
^Ino field package.preload['cmake-tools']
lazy_loader: module cmake-tools not found
lazy_loader_lib: module cmake-tools not found
^Ino file './cmake-tools.lua'
^Ino file '/usr/share/luajit-2.1.0-beta3/cmake-tools.lua'
^Ino file '/usr/local/share/lua/5.1/cmake-tools.lua'
^Ino file '/usr/local/share/lua/5.1/cmake-tools/init.lua'
^Ino file '/usr/share/lua/5.1/cmake-tools.lua'
^Ino file '/usr/share/lua/5.1/cmake-tools/init.lua'
^Ino file './cmake-tools.so'
^Ino file '/usr/local/lib/lua/5.1/cmake-tools.so'
^Ino file '/usr/lib/lua/5.1/cmake-tools.so'
^Ino file '/usr/local/lib/lua/5.1/loadall.so'
# stacktrace:
  - .config/nvim/lua/plugins/cmake.lua:4 _in_ **config**
  - .config/nvim/init.lua:1
```

I have cmake installed and used on my system before.
I tried adding `"Civitasv/cmake-tools.nvim",` to my `.config/nvim/plugins/init.lua` file, right after plenary is loaded.

How can I fix this problem?

os         Arch Linux
host     81T3 Legion Y540-17IRH-PG0
kernel 6.2.11-lqx3-1-lqx
nvim NVIM v0.9.0 Build type: Release
LuaJIT 2.1.0-beta3

**Comment by Civitasv** [comment]
https://github.com/Civitasv/runvim/blob/79b6c30f63a1949fe76ff633be05e9485b131fc3/lua/plugins/cmake.lua#L2

You can change this to `Civitasv/cmake-tools.nvim`

**Comment by cainydev** [comment]
I tried that now but doesn't have no effect: `dir = "Civitasv/cmake-tools.nvim",`
Also, I am wondering why is this `dir` variable never used in this file?

Are there any other options I could try? I don't even have the `personal` directory in `~/.local/share/nvim/`

**Comment by Civitasv** [comment]
I mean, change this entire line to "Civitasv/cmake-tools.nvim", you can google lazy.nvim to get more information about it.

**Comment by cainydev** [comment]
Thanks, I get it now, this `dir` variable is just one item of the object/array that is returned..
It works now :)
