### ISSUE TITLE
cmake tools in lualine

### ISSUE THREAD

**Issue by rsrehov** [Civitasv/nvimrc#6]
I'm trying to recreate your example that you mention in your cmake-tools plugin where you add all the build tools into the lualine along with the icons.  I copied the whole example.  I also copied your icons in your runvim repo into my own luafile and believe I called it correctly like you do in your example.  I also called the cmake-tools as well.  I was expecting to see all the icons in the lualine when I loaded some file but I don't see any.  Below shows my calls.  I have the icons in that location.  When I start up nvim I don't get any errors and I do see all of the lualine sections except for the cmake icons.  Do you know what may be going on? 

local cmake = require("cmake-tools")
local icons = require("core.icons")

**Comment by Civitasv** [comment]
It will show only if you are at a CMake project. And I've updated [docs](https://github.com/Civitasv/cmake-tools.nvim/blob/master/docs/howto.md#mimic-ui-of-cmake-tools-toolbar-in-visual-studio-code) about it in cmake-tools.nvim, maybe you can try again.

And sorry for my late, I don't see this message.
