### ISSUE TITLE
How to change "/runvim/lua/user" in your project is modified to adapt to lazyvim?

### ISSUE THREAD

**Issue by serendipitywgy** [Civitasv/nvimrc#7]
I would like to ask how to change "/runvim/lua/user" in your project is modified to adapt to lazyvim。

**Comment by serendipitywgy** [comment]
OK, I carefully understood the lualine code you provided and how to use lazyvim, and I have successfully achieved the desired effect.

**Comment by Civitasv** [comment]
Good to hear. Closing the issue for now, feel free to open it if you still have problems.
